### ISSUE TITLE
Using gTabulate with a newtype wrapper for a record type

### ISSUE THREAD

**Issue by dcastro** [paf31/purescript-memoize#10]
I'm having trouble defining an instance of `Tabulate` for my type.

```
import Data.Generic.Rep (class Generic)
import Data.Function.Memoize (class Tabulate, gTabulate)

newtype BuildType = BuildType
  { url :: String
  , name :: String
  , project :: String
  }

derive instance genericBuildType :: Generic BuildType _

instance tabulateBuildType :: Tabulate BuildType where
  tabulate = gTabulate
```

This fails with:

```
Error found:
in module Model
at d:\Dropbox\Projects\Purescript\tc-ui\tc-ui\src\Model.purs line 25, column 3 - line 25, column 23

  No type class instance was found for

    Data.Function.Memoize.Tabulate (Rec (Product (Field "name" String) (Product (Field "project" String) (Field "url" String))))


while checking that expression Tabulate { "tabulate": gTabulate
                                        }
  has type { "tabulate" :: forall r. (BuildType -> r) -> BuildType -> Lazy r
           }
while checking that type forall a r rep.
                           ( Generic a rep
                           , Tabulate rep
                           ) => (a -> r) -> a -> Lazy r
  is at least as general as type (BuildType -> r0) -> BuildType -> Lazy r0
in value declaration tabulateBuildType

where r0 is a rigid type variable
        bound at line 25, column 3 - line 25, column 23

See https://github.com/purescript/documentation/blob/master/errors/NoInstanceFound.md for more information,
or to contribute content related to this error
```

Am I doing anything wrong? Or is this a known limitation?

Thank you

**Comment by paf31** [comment]
This is a known limitation right now. The library doesn't support records yet. It could though, if we add the right instances.

**Comment by dcastro** [comment]
Thank you for your prompt response. 

If you don't mind me asking, it's only day 3 in my purescript journey, how would I go about implementing an ad-hoc instance of `Tabulate BuildType`?

**Comment by paf31** [comment]
It would probably be quicker to add generic support, to be honest 😄 

If you really wanted to make an ad-hoc instance, you could do it by treating the record like a nested tuple (have a look at the instance for `Tuple`, for example)

**Comment by dcastro** [comment]
The tuple hint worked for me :D

I tried creating an instance of `Tabulate` for records, to see if I could submit a PR for it, but I don't know how to abstract over property names... I suppose I should be using `Generic`. I _may_ look back into this if I find the time...

Cheers!
