### ISSUE TITLE
Add link to `Elegant memoization` from Conal Elliott 

### ISSUE THREAD

**Issue by safareli** [paf31/purescript-memoize#12]
Once I saw implementation of this lib [Elegant memoization](http://conal.net/talks/elegant-memoization.pdf) came to my mind. and thought that it might be good for curious reader to take a look at the slides.

**Comment by safareli** [comment]
It also has laws, which could be adopted
```
trie (untrie a) = a
untrie (trie f ) = f
```

**Comment by paf31** [comment]
Well this library doesn't use an intermediate trie data type, at least not one which is visible in the API. The closest library would probably be `data-memocombinators`. That said, I wouldn't be against adding links to relevant papers/libraries.
